quarkus.application.name=kafka-transaction-processor
quarkus.http.port=8080

%prod.kafka.bootstrap.servers=${KAFKA_BOOTSTRAP_SERVERS:localhost:9092}
quarkus.kafka.devservices.provider=strimzi
%test.quarkus.kafka.devservices.enabled=false

mp.messaging.incoming.transactions-in.connector=smallrye-kafka
mp.messaging.incoming.transactions-in.topic=transactions-raw
mp.messaging.incoming.transactions-in.group.id=transaction-processor
mp.messaging.incoming.transactions-in.auto.offset.reset=earliest
mp.messaging.incoming.transactions-in.value.deserializer=org.apache.kafka.common.serialization.StringDeserializer

mp.messaging.outgoing.transactions-enriched-out.connector=smallrye-kafka
mp.messaging.outgoing.transactions-enriched-out.topic=transactions-enriched
mp.messaging.outgoing.transactions-enriched-out.value.serializer=io.quarkus.kafka.client.serialization.ObjectMapperSerializer

mp.messaging.outgoing.transactions-dlq-out.connector=smallrye-kafka
mp.messaging.outgoing.transactions-dlq-out.topic=transactions-dlq
mp.messaging.outgoing.transactions-dlq-out.value.serializer=io.quarkus.kafka.client.serialization.ObjectMapperSerializer

mp.messaging.outgoing.transactions-raw-out.connector=smallrye-kafka
mp.messaging.outgoing.transactions-raw-out.topic=transactions-raw
mp.messaging.outgoing.transactions-raw-out.value.serializer=org.apache.kafka.common.serialization.StringSerializer

quarkus.datasource.db-kind=h2
quarkus.datasource.jdbc.url=jdbc:h2:mem:transactions;DB_CLOSE_DELAY=-1
quarkus.datasource.username=sa
quarkus.datasource.password=
quarkus.hibernate-orm.database.generation=drop-and-create
%dev.quarkus.hibernate-orm.log.sql=true
